locations:
  spawn: []
messages:
  locations:
    setspawn:
      noperms: '&cSetSpawn 8| &fУ Вас нет прав.'
      msg: '&aSetSpawn &8| &fНовая точка спавна установлена!'
    spawn:
      noperms: '&cSpawn &8| &fУ Вас нет прав.'
      msg: '&aSpawn &8| &fВы телепорированы на точку спавна!'
    setwarp:
      noperms: '&cSetWarp 8| &fУ Вас нет прав.'
      usage: '&6SetWarp &8| &fИспользуйте - &6/setwarp [имя]'
      msg: '&aSetWarp &8| &fВарп &a{warp} &fустановлен!'
    warp:
      notexists: '&cWarp &8| &fВарп не существует!'
      noperms: '&cWarp &8| &fУ Вас нет прав.'
      usage: '&6Warp &8| &fИспользуйте - &6/warp [имя]'
      msg: '&aWarp &8| &fВы телепорированы на  варп &a{warp}'
  ask:
    noperms: '&cAsk &8| &fУ Вас нет прав.'
    usage: '&6Ask &8| &fИспользуйте - &6/chat [сообщение]'
    send: '&aAsk &8| &fВаш вопрос успешно отправлен модераторам в сети!'
    adminmode:
      message: |-
        &a&m&l----------------------------------
        &6Ask &8| &fПришел новый вопрос от {sender}
        &6• &fВопрос: &e{message}
        &a&m&l----------------------------------
      reply:
        usage: '&6Ask &8| &fИспользуйте - &6/askreply [ник] [сообщение]'
        send: '&aAsk &8| &fВаш ответ был отправлен {player}'
        reply: |-
          &a&m&l----------------------------------
          &6Ask &8| &fВам пришел ответ от {sender}
          &6• &fОтвет: &e{reply}
          &a&m&l----------------------------------
  report:
    noperms: '&cReport &8| &fУ Вас нет прав.'
    usage: '&6Reports &8| &fИспользуйте - &6/report [ник] [причина]'
    send: '&aReports &8| &fВаша жалоба на {player} &fучтена!'
    adminmode:
      message: |-
        &a&m&l----------------------------------
        &6Reports &8| &fПришла новая жалоба от {sender}
        &6• &fЖалоба на: {player}
        &6• &fПричина: &e{reason}
        &a&m&l----------------------------------
  msg:
    notonline: '&cMessages &8| &fДанный игрок не в сети!'
    noperms: '&cMessages &8| &fУ Вас нет прав.'
    usage: '&6Messages &8| &fИспользуйте - &6/message [ник] [сообщение]'
    msgformat:
      to: '&6Messages &8| {player} &fнаписал Вам: &7{message}'
      you: '&aMessages &8| &fВы написали {player}&f: &7{message}'
  memory:
    usage: |-
      &6Memory &8| &fИнформация о сервере: &6{server}
      &6• &fВыделено памяти: &e{maxMemory}
      &6• &fСвободно памяти: &e{freeMemory}
      &6• &fЗанято памяти: &e{totalMemory}
  call:
    requestmsg: |-
      &a&m&l----------------------------------
      &6Teleport &8| &fВам пришел запрос от {player}
      &6• &fЧтобы &aпринять &fтелепортацию - &6/tpaccept
      &6• &fЧтобы &cотклонить &fтелепортацию - &6/tpadeny
      &a&m&l----------------------------------
    noperms: '&cTeleport &8| &fУ Вас нет прав.'
    send: '&aTeleport &8| &fВаш запрос на телепортацию отправлен {player}'
    usage: '&6Teleport &8| &fИспользуйте - &6/call [ник]'
    notrequests: '&cTeleport &8| &fУ Вас нет ожидаемых запрососв!'
    accept:
      accept: '&aTeleport &8| {player} &fпринял Ваш запрос на телепортацию!'
    deny:
      deny: '&cTeleport &8| {player} &fотклнонил Ваш запрос на телепортацию!'
  chat:
    join: '&6+ &fНа сервер присоединился {player}'
    format: '%prefix%player &8» %suffix%message'
    clear:
      noperms: '&cChatClear &8| &fУ Вас нет прав.'
      send: '&6ChatClear &8| &fЧат очищен {player}'
    staff:
      notplayer: 'You are not player!'
      noperms: '&cStaffChat &8| &fУ Вас нет прав.'
      usage: '&6StaffChat &8| &fИспользуйте - &6/sc [сообщение]'
      send: ' &e[Чат персонала] {player}&f: {message}'
    broadcast:
      notplayer: 'You are not player!'
      noperms: '&cBroadcast &8| &fУ Вас нет прав.'
      usage: '&6Broadcast &8| &fИспользуйте - &6/bc [сообщение]'
      send: '&c&l[ОБЪЯВЛЕНИЕ] {player}&f: {message}'
  gamemode:
    notplayer: 'You are not player!'
    noperms: '&cGameMode &8| &fУ Вас нет прав.'
    usage: '&6GameMode &8| &fИспользуйте - &6/gm 0/1/2/3'
    creative: '&aGameMode &8| &fРежим &aКреатив &fбыл выдан игроку {player}'
    survival: '&aGameMode &8| &fРежим &aВыживание &fбыл выдан игроку {player}'
    adventure: '&aGameMode &8| &fРежим &aПриключение &fбыл выдан игроку {player}'
    spectator: '&aGameMode &8| &fРежим &aНаблюдатель &fбыл выдан игроку {player}'
  heal:
    noperms: '&cHeal &8| &fУ Вас нет прав.'
    notplayer: 'You are not player!'
    usage: '&aHeal &8| &fВы успешно исцелили себя.'
  feed:
    noperms: '&cFeed &8| &fУ Вас нет прав.'
    notplayer: 'You are not player!'
    usage: '&aFeed &8| &fВы успешно покормили себя.'
  vanish:
    noperms: '&cVanish &8| &fУ Вас нет прав.'
    notplayer: 'You are not player!'
    true: '&aVanish &8| &fВы успешно &aвключили &fрежим невидимости'
    false: '&aVanish &8| &fВы успешно &cвыключили &fрежим невидимости'
  essentiels:
    notplayer: 'You are not player!'
    reload: '&aEssentiels &8| &fКонфигурации успешно перезагружены.'
    noperms: '&cEssentiels &8| &fУ Вас нет прав.'
  bans:
    unban:
      usage: '&6Pardon &8| &fИспользуйте - &6/unban [ник]'
      msg: '&aPardon &8| &fВы успешно разбанили {player}'
      notbanned: '&cPardon &8| &fДанный игрок не в бане!'
    noperms: '&cBan &8| &fУ Вас нет прав.'
    notonline: '&cBan &8| &fДанный игрок не в сети!'
    usage: '&6Ban &8| &fИспользуйте - &6/ban [ник] [причина]'
    bannedmsg: '&aBan &8| &fВы успешно забанили игрока {player}'
    bannedallmsg: |-
      &6Ban &8| {player} &fбыл забанен {sender}
      &6• &fПричина: &e{reason}
  god:
    true: '&aGod &8| &fВы успешно &aвключили &fрежим Бога'
    false: '&aGod &8| &fВы успешно &cвыключили &fрежим Бога'
  fly:
    notplayer: 'You are not player!'
    noperms: '&cFly &8| &fУ Вас нет прав.'
    true: '&aFly &8| &fРежим полета: &aвключен'
    false: '&aFly &8| &fРежим полета: &cвыключен'
  inventory:
    notplayer: 'You are not player!'
    noperms: '&cInventory &8| &fУ Вас нет прав.'
    clear: '&aInventory &8| &fВаш инвентарь успешно очищен!'
  kick:
    noperms: '&cKick &8| &fУ Вас нет прав.'
    usage: '&6Kick &8| &fИспользуйте - &6/kick [ник] [причина]'
    sendermsg: '&aKick &8| &fВы успешно кикнули {player}'
    notonline: '&cKick &8| &fДанного игрока нет в онлайне!'
    all: '&aKick &8| &fВы успешно кикнули всех игроков!'
    allmsg: |-
        &6Kick &8| {player} &fбыл кикнут {sender}
        &6• &fПричина: &e{reason}
